---
title: "YY1 ChIA-PET motif analysis (single call)"
author: "Jennifer Hammelman, Konstantin Krismer"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{YY1 ChIA-PET motif analysis (single call)}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, message=FALSE}
set.seed(17)
library(spatzie)
```

# Load data

```{r load_interactions}
yy1_interactions_file <- system.file("extdata/yy1_interactions.bedpe.gz",
                                     package = "spatzie")
int_data_df <- read.table(gzfile(yy1_interactions_file), header = TRUE,
                          sep = "\t")

motifs_file <- system.file("extdata/motifs_subset.txt.gz",
                           package = "spatzie")
```

# Run spatzie enhancer-promoter motif co-enrichment analysis

```{r load_promoters}
res <- spatzie::find_ep_coenrichment(int_data_df, motifs_file,
                                     motifs_file_matrix_format = "pfm",
                                     genome_id = "mm9",
                                     cooccurrence_method = "count")
```

# Results

## Interaction type pie chart

```{r annotate_interactions, message=FALSE, warning=FALSE}
plot(res$annotation_pie_chart)
```

## Motif co-enrichment matrix

```{r compute_cosignificance_count}
pheatmap::pheatmap(-log2(res$motif_cooccurrence$pair_motif_enrich), fontsize = 6)
```
